# Generated by Django 6.0.6 on 2026-06-30 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projectmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=100, verbose_name='接口路径')),
                ('description', models.TextField(blank=True, verbose_name='接口描述')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Query参数')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('is_active', models.BooleanField(verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_api_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'db_table': 'interfaces_api_endpoint',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'method', 'path')},
            },
        ),
    ]
