# Generated by Django 6.0.6 on 2026-06-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='apiendpoint',
            name='path',
            field=models.CharField(max_length=255, verbose_name='接口路径'),
        ),
    ]
