# Generated by Django 6.0.6 on 2026-07-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projectmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('base_url', models.URLField(verbose_name='基础地址')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='环境变量')),
                ('description', models.TextField(blank=True, verbose_name='环境描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'environments_environment',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
