# Generated by Django 6.0.6 on 2026-07-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('projects', '0002_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('project',), name='unique_active_default_environment'),
        ),
    ]
