# Generated by Django 6.0.6 on 2026-06-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', '拥有者'), ('admin', '管理者'), ('member', '成员'), ('viewer', '只读成员')], max_length=20, verbose_name='角色'),
        ),
    ]
