# Generated by Django 6.0.6 on 2026-07-23 03:20

from django.db import migrations, models


def convert_admin_to_member(apps, schema_editor):
    ProjectMember = apps.get_model('projects', 'ProjectMember')
    ProjectMember.objects.filter(role='admin').update(role='member')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmember_role'),
    ]

    operations = [
        migrations.RunPython(
            convert_admin_to_member,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', '拥有者'), ('member', '成员'), ('viewer', '只读成员')], max_length=20, verbose_name='角色'),
        ),
    ]
