# Generated by Django 6.0.6 on 2026-07-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('interfaces', '0002_alter_apiendpoint_is_active_alter_apiendpoint_path'),
        ('projects', '0002_alter_projectmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头覆盖')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Query 参数覆盖')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体覆盖')),
                ('expected_status_code', models.PositiveIntegerField(default=200, verbose_name='期望状态码')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='断言规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='interfaces.apiendpoint', verbose_name='关联接口')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='environments.environment', verbose_name='运行环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'testcases_test_case',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
