# Generated by Django 6.0.6 on 2026-07-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('projects', '0002_alter_projectmember_role'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '异常')], default='pending', max_length=20, verbose_name='执行状态')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('request_url', models.URLField(blank=True, max_length=500, verbose_name='请求 URL')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_query_params', models.JSONField(blank=True, default=dict, verbose_name='Query 参数')),
                ('request_body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name='响应体')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='environments.environment', verbose_name='运行环境')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='projects.project', verbose_name='所属项目')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试执行记录',
                'verbose_name_plural': '测试执行记录',
                'db_table': 'executions_test_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
