# Generated by Django 6.0.6 on 2026-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='failure_message',
            field=models.TextField(blank=True, verbose_name='断言失败原因'),
        ),
    ]
