# Generated by Django 6.0.6 on 2026-07-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_environment_unique_active_default_environment'),
        ('executions', '0002_testexecution_failure_message'),
        ('projects', '0002_alter_projectmember_role'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='批次名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('error', '异常')], default='pending', max_length=20, verbose_name='批次状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总用例数')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='已完成数')),
                ('passed_count', models.PositiveIntegerField(default=0, verbose_name='通过数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='异常数')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='总耗时毫秒')),
                ('error_message', models.TextField(blank=True, verbose_name='批次错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project', verbose_name='所属项目')),
                ('test_cases', models.ManyToManyField(related_name='test_runs', to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试批次',
                'verbose_name_plural': '测试批次',
                'db_table': 'executions_test_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='executions.testrun', verbose_name='所属批次'),
        ),
        migrations.AddConstraint(
            model_name='testexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('test_run__isnull', False)), fields=('test_run', 'test_case'), name='unique_test_case_per_test_run'),
        ),
    ]
